# Generated by Django 3.2 on 2021-05-19 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ref_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
