# Generated by Django 3.2 on 2021-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('RENT', 'RENT'), ('FEES', 'FEES'), ('OTHERS', 'OTHERS')], default=[('FOOD', 'FOOD'), ('RENT', 'RENT'), ('FEES', 'FEES'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
