# Generated by Django 3.2 on 2021-05-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20210520_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('RENT', 'RENT'), ('FEES', 'FEES'), ('OTHERS', 'OTHERS')], default='FOOD', max_length=255),
        ),
    ]
