# Generated by Django 3.2 on 2021-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_alter_categories_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='ref_number',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('FOOD', 'FOOD'), ('RENT', 'RENT'), ('FEES', 'FEES'), ('OTHERS', 'OTHERS')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
